version: '3'

services:
  mysql:
    image: mysql:5.7.22
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: server_go
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./.docker/mysql/dbdata:/var/lib/mysql
